# Generated by Django 6.0.6 on 2026-07-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
