# Generated by Django 6.0.6 on 2026-07-11 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('doctor', 'appointment_date', 'time_slot'), name='unique_doctor_slot', violation_error_message='This slot is already booked for this doctor.'),
        ),
    ]
