# Generated by Django 6.0.6 on 2026-07-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', models.CharField(choices=[('EVERYDAY', 'Every day'), ('WEEKDAYS', 'Weekdays (Mon-Fri)'), ('MON_SAT', 'Mon to Sat'), ('DATE', 'Specific date')], default='EVERYDAY', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('breaks', models.JSONField(blank=True, default=list)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
