# Generated by Django 6.0.6 on 2026-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
