# Generated by Django 6.0.6 on 2026-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General Medicine'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPAEDICS', 'Orthopaedics'), ('DERMATOLOGY', 'Dermatology'), ('ENT', 'ENT'), ('PAEDIATRICS', 'Paediatrics')], max_length=20),
        ),
    ]
